export const BuildingSprites = {
    bank: [
        "map/map-building-bank-ceiling-01.svg",
        "map/map-building-bank-ceiling-02.svg",
        "map/map-building-bank-ceiling-03.svg",
        "map/map-building-bank-floor-01.svg",
        "map/map-building-bank-floor-02.svg",
        "map/map-building-bank-window-01.svg",
        "map/map-building-bank-window-res-01.svg",
        "map/map-building-vault-ceiling.svg",
    ],

    barn: [
        "map/map-building-barn-basement-ceiling-01.svg",
        "map/map-building-barn-basement-ceiling-02.svg",
        "map/map-building-barn-basement-floor-01.svg",
        "map/map-building-barn-basement-floor-02.svg",
        "map/map-building-barn-basement-stairs.svg",
        "map/map-building-barn-ceiling-01.svg",
        "map/map-building-barn-ceiling-02.svg",
        "map/map-building-barn-floor-01.svg",

        "map/map-building-panicroom-ceiling.svg",
        "map/map-building-panicroom-floor.svg",
    ],

    cabin: [
        "map/map-building-boarded-window-01.svg",
        "map/map-building-bridge-lg-ceiling.svg",
        "map/map-building-bridge-lg-floor.svg",
        "map/map-building-bridge-md-floor.svg",
        "map/map-building-cabin-ceiling-01a.svg",
        "map/map-building-cabin-ceiling-01b.svg",
        "map/map-building-cabin-floor.svg",
    ],

    club: [
        "map/map-building-bathhouse-basement-01a.svg",
        "map/map-building-bathhouse-basement-01b.svg",
        "map/map-building-bathhouse-basement-01c.svg",
        "map/map-building-bathhouse-basement-01d.svg",
        "map/map-building-bathhouse-basement-01e.svg",
        "map/map-building-bathhouse-sideroom-01.svg",
        "map/map-building-bathhouse-sideroom-02.svg",
        "map/map-building-bathhouse-sideroom-ceiling-01.svg",
        "map/map-building-bathhouse-sideroom-ceiling-02.svg",

        "map/map-building-club-ceiling-01a.svg",
        "map/map-building-club-ceiling-01b.svg",
        "map/map-building-club-ceiling-01c.svg",
        "map/map-building-club-floor-01a.svg",
        "map/map-building-club-floor-01b.svg",
        "map/map-building-club-floor-01c.svg",
        "map/map-building-club-floor-01d.svg",
        "map/map-building-club-floor-01e.svg",
        "map/map-building-club-floor-01f.svg",
        "map/map-building-club-floor-01g.svg",
        "map/map-building-club-floor-01h.svg",
        "map/map-building-club-vault-ceiling.svg",
        "map/map-bathhouse-column-01.svg",
        "map/map-bathhouse-pool-01.svg",
    ],

    container: [
        "map/map-building-container-ceiling-01.svg",
        "map/map-building-container-ceiling-02.svg",
        "map/map-building-container-ceiling-03.svg",
        "map/map-building-container-ceiling-05.svg",
        "map/map-building-container-floor-01.svg",
        "map/map-building-container-open-ceiling-01.svg",
        "map/map-building-container-open-floor.svg",
    ],

    dock: ["map/map-building-dock-floor-01a.svg", "map/map-building-dock-floor-01b.svg"],

    greenhouse: [
        "map/map-building-greenhouse-ceiling-01.svg",
        "map/map-building-greenhouse-floor-01.svg",
        "map/map-planter-01.svg",
        "map/map-planter-02.svg",
        "map/map-planter-03.svg",
        "map/map-planter-04.svg",
        "map/map-planter-05.svg",
        "map/map-planter-07.svg",
        "map/map-planter-res-01.svg",
        "map/map-planter-res-03.svg",
    ],

    greenhouse_aged: [
        "map/map-building-greenhouse-ceiling-02.svg",
        "map/map-building-greenhouse-floor-02.svg",
        "map/map-planter-06.svg",
        "map/map-planter-07.svg",
        "map/map-planter-res-02.svg",
        "map/map-planter-res-03.svg",
    ],

    house_red: [
        "map/map-building-house-ceiling.svg",
        "map/map-building-house-floor-01.svg",
        "map/map-building-house-floor-02.svg",
        "map/map-building-house-window-01.svg",
        "map/map-building-house-window-res-01.svg",
    ],

    hut: [
        "map/map-building-hut-ceiling-01.svg",
        "map/map-building-hut-ceiling-02.svg",
        "map/map-building-hut-ceiling-03.svg",
        "map/map-building-hut-floor-01.svg",
        "map/map-building-hut-floor-02.svg",
    ],

    large_hut: [
        "map/map-building-hut-ceiling-04.svg",
        "map/map-building-hut-floor-03.svg",
        "map/map-hut-res-02.svg",
    ],

    mansion: [
        "map/map-building-mansion-ceiling.svg",
        "map/map-building-mansion-cellar-01a.svg",
        "map/map-building-mansion-cellar-01b.svg",
        "map/map-building-mansion-cellar-01c.svg",
        "map/map-building-mansion-floor-01a.svg",
        "map/map-building-mansion-floor-01b.svg",
        "map/map-building-mansion-floor-01c.svg",
        "map/map-building-mansion-floor-01d.svg",

        "map/map-building-saferoom-ceiling.svg",
        "map/map-building-saferoom-floor.svg",
    ],

    outhouse: [
        "map/map-building-outhouse-ceiling.svg",
        "map/map-building-outhouse-floor.svg",
    ],

    pavilion: [
        "map/map-building-pavilion-ceiling-01.svg",
        "map/map-building-pavilion-floor-01.svg",
        "map/map-building-pavilion-res-01.svg",
    ],

    police: [
        "map/map-building-police-ceiling-01.svg",
        "map/map-building-police-ceiling-02.svg",
        "map/map-building-police-ceiling-03.svg",
        "map/map-building-police-floor-01.svg",
        "map/map-building-police-floor-02.svg",
    ],

    reserve: [
        "map/map-building-reserve-basement-floor-01.svg",
        "map/map-building-reserve-basement-floor-02.svg",
        "map/map-building-reserve-basement-floor-03.svg",
        "map/map-building-reserve-basement-floor-04.svg",
        "map/map-building-reserve-basement-floor-05.svg",
        "map/map-building-reserve-ceiling-01.svg",
        "map/map-building-reserve-ceiling-02.svg",
        "map/map-building-reserve-ceiling-03.svg",
        "map/map-building-reserve-ceiling-04.svg",
        "map/map-building-reserve-floor-01.svg",
        "map/map-building-reserve-floor-02.svg",
        "map/map-building-reserve-floor-03.svg",
        "map/map-building-reserve-floor-04.svg",
        "map/map-building-reserve-sideroom-01.svg",
        "map/map-building-reserve-sideroom-02.svg",
        "map/map-building-reserve-sideroom-ceiling-01.svg",
        "map/map-building-reserve-sideroom-ceiling-02.svg",
        "map/map-building-reserve-window-01.svg",
        "map/map-building-reserve-window-res-01.svg",
        "map/map-building-reserve-vault-01.svg",
        "map/map-building-reserve-vault-ceiling-01.svg",
        "map/map-door-06.svg",
        "map/map-door-slot-03.svg",
        "map/map-reserve-bar-01.svg",
        "map/map-reserve-bar-large.svg",
        "map/map-stairs-broken-02.svg",
        "map/map-stairs-broken-03.svg",
    ],

    saloon: [
        "map/map-building-saloon-ceiling-01.svg",
        "map/map-building-saloon-ceiling-02.svg",
        "map/map-building-saloon-cellar-01.svg",
        "map/map-building-saloon-floor-01.svg",
    ],

    shacks: [
        "map/map-building-shack-ceiling-01.svg",
        "map/map-building-shack-ceiling-02.svg",
        "map/map-building-shack-ceiling-03.svg",
        "map/map-building-shack-floor-01.svg",
        "map/map-building-shack-floor-02.svg",
        "map/map-building-shack-floor-03.svg",
        "map/map-shack-res-01.svg",
        "map/map-shack-res-02.svg",
        "map/map-shack-res-03.svg",
    ],

    shilo: [
        "map/map-building-shilo-ceiling-01.svg",
        "map/map-building-shilo-floor-01.svg",
    ],

    teahouse: [
        "map/map-building-teahouse-ceiling-01.svg",
        "map/map-building-teahouse-floor-01.svg",
        "map/map-building-teahouse-floor-02.svg",
        "map/map-building-teahouse-res-01.svg",
    ],

    warehouse_complex: [
        "map/map-complex-warehouse-floor-01.svg",
        "map/map-complex-warehouse-floor-02.svg",
        "map/map-complex-warehouse-floor-03.svg",
    ],

    warehouses: [
        "map/map-building-warehouse-ceiling-01.svg",
        "map/map-building-warehouse-ceiling-02.svg",
        "map/map-building-warehouse-floor-01.svg",
        "map/map-building-warehouse-floor-02.svg",
        "map/map-building-warehouse-floor-03.svg",
    ],

    workshop: [
        "map/map-building-workshop-floor-01.svg",
        "map/map-building-workshop-floor-02.svg",
        "map/map-building-workshop-ceiling-01.svg",
        "map/map-building-workshop-ceiling-02.svg",
    ],

    bunker_hydra: [
        "map/map-bunker-hydra-ceiling-01.svg",
        "map/map-bunker-hydra-chamber-ceiling-01.svg",
        "map/map-bunker-hydra-chamber-ceiling-02.svg",
        "map/map-bunker-hydra-chamber-ceiling-03.svg",
        "map/map-bunker-hydra-chamber-floor-01a.svg",
        "map/map-bunker-hydra-chamber-floor-01b.svg",
        "map/map-bunker-hydra-chamber-floor-02.svg",
        "map/map-bunker-hydra-chamber-floor-03.svg",
        "map/map-bunker-hydra-compartment-ceiling-01.svg",
        "map/map-bunker-hydra-compartment-ceiling-02.svg",
        "map/map-bunker-hydra-compartment-ceiling-03.svg",
        "map/map-bunker-hydra-compartment-floor-01.svg",
        "map/map-bunker-hydra-compartment-floor-02.svg",
        "map/map-bunker-hydra-compartment-floor-03.svg",
        "map/map-bunker-hydra-floor-01.svg",
        "map/map-bunker-hydra-floor-04.svg",
    ],

    bunker_crossing: [
        "map/map-building-crossing-bathroom-ceiling.svg",
        "map/map-bunker-crossing-ceiling-01.svg",
        "map/map-bunker-crossing-chamber-ceiling-01.svg",
        "map/map-bunker-crossing-chamber-floor-01a.svg",
        "map/map-bunker-crossing-chamber-floor-01b.svg",
        "map/map-bunker-crossing-chamber-floor-01c.svg",
        "map/map-bunker-crossing-chamber-floor-02.svg",
        "map/map-bunker-crossing-chamber-floor-03.svg",
        "map/map-bunker-crossing-compartment-ceiling-01a.svg",
        "map/map-bunker-crossing-compartment-ceiling-01b.svg",
        "map/map-bunker-crossing-compartment-floor-01.svg",
        "map/map-bunker-crossing-compartment-floor-02.svg",
        "map/map-bunker-crossing-floor-01.svg",
    ],

    bunker_hatchet: [
        "map/map-bunker-hatchet-chamber-ceiling-01.svg",
        "map/map-bunker-hatchet-chamber-floor-01a.svg",
        "map/map-bunker-hatchet-chamber-floor-01b.svg",
        "map/map-bunker-hatchet-chamber-floor-01c.svg",
        "map/map-bunker-hatchet-compartment-ceiling-01.svg",
        "map/map-bunker-hatchet-compartment-ceiling-02.svg",
        "map/map-bunker-hatchet-compartment-ceiling-03.svg",
        "map/map-bunker-hatchet-compartment-floor-01.svg",
        "map/map-bunker-hatchet-compartment-floor-02a.svg",
        "map/map-bunker-hatchet-compartment-floor-02b.svg",
        "map/map-bunker-hatchet-compartment-floor-02c.svg",
        "map/map-bunker-hatchet-compartment-floor-02d.svg",
        "map/map-bunker-hatchet-compartment-floor-03a.svg",
        "map/map-bunker-hatchet-compartment-floor-03b.svg",
        "map/map-bunker-hatchet-compartment-floor-03c.svg",
        "map/map-bunker-hatchet-compartment-floor-03d.svg",
    ],

    bunker_egg: [
        "map/map-bunker-egg-chamber-ceiling-01.svg",
        "map/map-bunker-egg-chamber-floor-01a.svg",
        "map/map-bunker-egg-chamber-floor-01b.svg",
    ],

    bunker_storm: [
        "map/map-bunker-storm-chamber-ceiling-01.svg",
        "map/map-bunker-storm-chamber-floor-01a.svg",
        "map/map-bunker-storm-chamber-floor-01b.svg",
        "map/map-bunker-storm-floor-02.svg",
    ],

    bunker_twins: [
        "map/map-bunker-twins-ceiling-01.svg",
        "map/map-bunker-twins-chamber-ceiling-01.svg",
        "map/map-bunker-twins-chamber-floor-01.svg",
        "map/map-bunker-twins-compartment-floor-01.svg",
    ],

    bunker_conch: [
        "map/map-bunker-conch-ceiling-01.svg",
        "map/map-bunker-conch-chamber-ceiling-01.svg",
        "map/map-bunker-conch-chamber-ceiling-02.svg",
        "map/map-bunker-conch-chamber-floor-01.svg",
        "map/map-bunker-conch-chamber-floor-02.svg",
        "map/map-bunker-conch-compartment-ceiling-01.svg",
        "map/map-bunker-conch-compartment-floor-01a.svg",
        "map/map-bunker-conch-compartment-floor-01b.svg",
        "map/map-bunker-conch-floor-01.svg",
    ],

    bunker_chrys: [
        "map/map-bunker-chrys-chamber-ceiling-01.svg",
        "map/map-bunker-chrys-chamber-floor-01a.svg",
        "map/map-bunker-chrys-chamber-floor-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-01a.svg",
        "map/map-bunker-chrys-compartment-ceiling-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-02a.svg",
        "map/map-bunker-chrys-compartment-ceiling-02b.svg",
        "map/map-bunker-chrys-compartment-ceiling-03a.svg",
        "map/map-bunker-chrys-compartment-ceiling-03b.svg",
        "map/map-bunker-chrys-compartment-floor-01a.svg",
        "map/map-bunker-chrys-compartment-floor-01b.svg",
        "map/map-bunker-chrys-compartment-floor-01d.svg",
        "map/map-bunker-chrys-compartment-floor-02a.svg",
        "map/map-bunker-chrys-compartment-floor-02b.svg",
        "map/map-bunker-chrys-compartment-floor-03a.svg",
    ],

    bunker_eye: [
        "map/map-bunker-eye-chamber-ceiling-01.svg",
        "map/map-bunker-eye-chamber-floor-01a.svg",
        "map/map-bunker-eye-chamber-floor-01b.svg",
        "map/map-bunker-eye-compartment-ceiling-01.svg",
        "map/map-bunker-eye-compartment-floor-01.svg",
        // removed tree switches...
        // "map/map-tree-switch-01.svg",
        // "map/map-tree-switch-02.svg",
        // "map/map-tree-switch-03.svg",
        // "map/map-tree-switch-04.svg",
    ],

    bunker_chrys_aged: [
        "map/map-bunker-chrys-chamber-ceiling-01.svg",
        "map/map-bunker-chrys-chamber-floor-01a.svg",
        "map/map-bunker-chrys-chamber-floor-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-01a.svg",
        "map/map-bunker-chrys-compartment-ceiling-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-02a.svg",
        "map/map-bunker-chrys-compartment-ceiling-02b.svg",
        "map/map-bunker-chrys-compartment-ceiling-03a.svg",
        "map/map-bunker-chrys-compartment-ceiling-03b.svg",
        "map/map-bunker-chrys-compartment-floor-01a.svg",
        "map/map-bunker-chrys-compartment-floor-01c.svg",
        "map/map-bunker-chrys-compartment-floor-02a.svg",
        "map/map-bunker-chrys-compartment-floor-02c.svg",
        "map/map-bunker-chrys-compartment-floor-03a.svg",
    ],
};
