export const Puzzles: Record<string, string[]> = {
    bunker_eye_02: ["egg", "hydra", "storm", "conch", "crossing", "hatchet"],
    bunker_eye_02_woods: [
        "swine",
        "hydra",
        "crossing",
        "hatchet",
        "harpsichord",
        "caduceus",
        "egg",
        "cloud",
        "storm",
        "conch",
    ],
    bunker_chrys_01: ["ichi", "ni", "san", "shi"],
    bunker_chrys_02: ["flower", "leaves", "moon", "frost"],
    saloon: ["red", "orange", "yellow", "green", "blue", "indigo", "violet"],
    club_01: ["1", "2", "3", "4"],
    club_02: ["1"],
    bunker_twins: ["scout", "sniper", "medic", "demo", "assault", "tank"],
    reserve_vault: ["1", "2", "3", "4", "2", "5"],
};
